server.port: 8082

spring:
  application:
    name: podcasts-ms

  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/podcasts?useSSL=false
    username: root