spring:
  application:
    name: mediabase

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  com.example.mediabase.podcastsUI: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
